<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.cybnity.application.access-control</groupId>
        <artifactId>adapters</artifactId>
        <version>${revision}</version>
        <relativePath>..</relativePath>
    </parent>
    <groupId>org.cybnity.application.access-control.adapters</groupId>
    <artifactId>keycloak-domain-ontology-impl</artifactId>
    <version>${revision}</version>
    <packaging>jar</packaging>
    <name>-- Keycloak domain ontology (impl)</name>

    <dependencies>
        <dependency>
            <groupId>org.keycloak</groupId>
            <artifactId>keycloak-client-common-synced</artifactId>
            <scope>compile</scope>
        </dependency>
    </dependencies>
</project>
