<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<artifactId>access-control</artifactId>
		<groupId>org.cybnity.application</groupId>
		<version>${revision}</version>
		<relativePath>..</relativePath>
	</parent>
	<groupId>org.cybnity.application.access-control</groupId>
	<artifactId>adapters</artifactId>
	<version>${revision}</version>
	<packaging>pom</packaging>
	<name>- AC domain adapters</name>
	<modules>
		<module>ac-adapter-api</module>
		<module>ac-adapter-admin-api</module>
		<module>keycloak-domain-ontology-impl</module>
		<module>ac-adapter-keycloak-impl</module>
		<module>ac-adapter-keycloak-admin-impl</module>
	</modules>

	<properties>
		<keycloak.authz-client.version>26.0.9</keycloak.authz-client.version>
		<keycloak.admin-client.version>26.0.9</keycloak.admin-client.version>
		<keycloak.client-common.version>26.0.9</keycloak.client-common.version>
	</properties>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<!-- Keycloak authorization client -->
				<!-- See https://www.keycloak.org/securing-apps/authz-client documentation -->
				<groupId>org.keycloak</groupId>
				<artifactId>keycloak-authz-client</artifactId>
				<version>${keycloak.authz-client.version}</version>
				<scope>compile</scope>
			</dependency>
			<dependency>
				<!-- Keycloak Admin REST client -->
				<groupId>org.keycloak</groupId>
				<artifactId>keycloak-admin-client</artifactId>
				<version>${keycloak.admin-client.version}</version>
				<scope>compile</scope>
			</dependency>
			<dependency>
				<groupId>org.keycloak</groupId>
				<artifactId>keycloak-client-common-synced</artifactId>
				<version>${keycloak.client-common.version}</version>
				<scope>compile</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>
</project>
